### PR TITLE
dts: msm8916: Add ARK Benefit A3 (peach)

### PR DESCRIPTION
**Pull request by entrider**

### CODE REVIEW

**Comment by stephan-gh** [comment]
This looks like it should be `msm8916-qrd4-v1.dts`. Can you try setting it up like this? Basically copy e.g. `msm8916-qrd8-v1.dts` and then change the `/8` in the `compatible` to `/4`. And add your device as subnode.

**Comment by entrider** [comment]
Should I keep this?
```
#include "msm8916-wingtech-wt865x8.dtsi"
```

**Comment by stephan-gh** [comment]
No.

**Comment by entrider** [comment]
@stephan-gh do you mean like this: https://github.com/entrider/lk2nd/commit/fc83df7bfaba6e72203726d45e62213f97d389f2

**Comment by stephan-gh** [comment]
You need something to match the device. Could be something on the cmdline from the primary bootloader or the list of panels like for other devices.

**Comment by entrider** [comment]
Done in #125.

**Pull request closed without merging**
