### PR TITLE
Add serial-number node to DTB when booting mainline (experimental-tmp)

### PR DESCRIPTION
**Pull request by FieryFlames**

### CODE REVIEW

**Comment by stephan-gh** [comment]
Why? Is this a standardized property?

**Comment by FieryFlames** [comment]
Yes, it's in device tree spec 0.4

**Comment by stephan-gh** [comment]
This question still stands though: Why? :)

**Comment by FieryFlames** [comment]
Just more device personalization, it ideally would be shown in settings but I haven't checked if thats implemented in phosh or plasma yet. Not really necessary tbh.. I saw it being done in m1n1 for Apple machines and wanted to try it here, but I guess it makes more sense there.

**Comment by stephan-gh** [comment]
AFAICT this is only read by Linux on ARM32, and only to show it in `/proc/cpuinfo` (wtf). It doesn't really seem to be used for anything :confused:

**Comment by FieryFlames** [comment]
Is that just in the kernel? Maybe userspace does more with it?

**Comment by stephan-gh** [comment]
I wouldn't expect userspace to read `/sys/firmware/device-tree/base/...` personally :thinking:

**Comment by samueldr** [comment]
Given it's specified as a required property in the spec, I think this alone should trump any other "but why?" questions.

**Comment by stephan-gh** [comment]
> Given it's specified as a required property in the spec, I think this alone should trump any other "but why?" questions.

@samueldr No, it's marked as O (= Optional). It's not even OR (= Optional but Recommended) :)

**Comment by samueldr** [comment]
Oh, oops, my bad. I missed the legend and the column, and assumed the wording in 3.1 and the note meant all properties were required.

**Comment by samueldr** [comment]
Are there other ways the OS can ask/request for the serial number of the device? If there are, I guess it doesn't matter then.

**Comment by stephan-gh** [comment]
> Are there other ways the OS can ask/request for the serial number of the device? If there are, I guess it doesn't matter as much then.

The serial number is usually just taken from the eMMC/UFS/flash and is probably available there through sysfs or similar.

I guess I'm not opposed to add the `serial-number`, but the changes itself need some more thought:

- `lk2nd_dev.serialno` exists only for lk2nd configurations but not on lk1st. This won't compile correctly there (this is not tested properly by CI atm).
- The whole thing probably should not be part of the device module but separate (similar to `lk2nd/mac` since LK usually has its own serial number.

**Comment by FieryFlames** [comment]
Will sort out those issues. I wasn't sure whether or not it should go in a separate module or in device, because panel is in device and mac isn't

**Comment by stephan-gh** [comment]
> because panel is in device and mac isn't

Because panel actually requires information from the device DTS, while MAC does not :)

**Comment by stephan-gh** [comment]
Integrated into experimental-tmp-gpio, thanks!

**Pull request closed without merging**
