### PR TITLE
dev_tree: Allow mapping power key

### PR DESCRIPTION
**Pull request by timbz**
Allows entering fastboot mode on the Huawei Watch using the (single) power button.

### CODE REVIEW

**Review by TravMurav — APPROVED** [review]
This looks good to me, I suppose you've tested already that resin isn't tied to the same button? (on lenok they're both tied together so it works "as is" by holding the key long enough)

**Comment by timbz** [comment]
> This looks good to me, I suppose you've tested already that resin isn't tied to the same button? (on lenok they're both tied together so it works "as is" by holding the key long enough)

Ye I did. I tried all sorts of patterns. There was no way to enter fastboot mode for me.

**Comment by stephan-gh** [comment]
Can you split this into two commits, one for `dts: ...` and one for `target: keys_lk2nd: ...` or something like that? The `dev_tree: ...` does not seem right.

**Comment by timbz** [comment]
> Can you split this into two commits, one for `dts: ...` and one for `target: keys_lk2nd: ...` or something like that? The `dev_tree: ...` does not seem right.

done

**Pull request merged**
